import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-slate-900">
        <h2 className="text-center font-bold text-2xl text-white">Jogo de Lagoa dos Patos MG</h2>
        <div className="w-[900px] m-auto overflow-hidden bg-slate-300">          
        {children}
        </div>
      </body>
    </html>
  );
}
